### Create a new patient entity
POST http://localhost:4000/api/v1/patients

Content-Type: application/json

{
    "name" : "Anish Shrestha",
    "email" : "anish@gmail.com",
    "address" : "Balaju-16, Kathmandu",
    "dateOfBirth" : "2004-04-21"
}

###